# Generated by Django 5.1.7 on 2025-03-19 09:06

import form_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='contact',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=form_app.models.upload_path),
        ),
    ]
