# Generated by Django 5.1.7 on 2025-03-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_alter_contact_uploaded_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('name', 'email')},
        ),
    ]
